-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    city_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(50) NOT NULL,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.cover_letter
(
    cover_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cover_description character varying(500) NOT NULL,
    PRIMARY KEY (cover_id)
);

CREATE TABLE public.cv_educations
(
    education_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    school_name character varying(100) NOT NULL,
    department character varying(100) NOT NULL,
    gpa_score character varying(10) NOT NULL,
    graduate_date date NOT NULL,
    PRIMARY KEY (education_id)
);

CREATE TABLE public.cv_experiences
(
    experience_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    workplace_name character varying(100) NOT NULL,
    position_name character varying(50) NOT NULL,
    work_description character varying(250) NOT NULL,
    start_date date NOT NULL,
    finish_date date NOT NULL,
    PRIMARY KEY (experience_id)
);

CREATE TABLE public.cv_foreignlang
(
    lang_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    lang_name character varying(250) NOT NULL,
    lang_level character varying(20) NOT NULL,
    PRIMARY KEY (lang_id)
);

CREATE TABLE public.cv_image
(
    image_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    image_url character varying(250) NOT NULL,
    PRIMARY KEY (image_id)
);

CREATE TABLE public.cv_informations
(
    cv_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    image_id integer NOT NULL,
    education_id integer NOT NULL,
    experience_id integer NOT NULL,
    skill_id integer NOT NULL,
    lang_id integer NOT NULL,
    social_id integer NOT NULL,
    user_id integer NOT NULL,
    "cover_.id" integer NOT NULL,
    PRIMARY KEY (cv_id)
);

CREATE TABLE public.cv_skills
(
    skill_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    skill_name character varying(100) NOT NULL,
    skill_degree character varying(20) NOT NULL,
    PRIMARY KEY (skill_id)
);

CREATE TABLE public.cv_socialmedia
(
    social_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    account_url_github character varying(500) NOT NULL,
    account_url_linkedin character varying(500) NOT NULL,
    PRIMARY KEY (social_id)
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    employees_id integer NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    company_name character varying(250) NOT NULL,
    web_address character varying(250) NOT NULL,
    phone_number character varying(11) NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_positions
(
    position_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "position" character varying(50) NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public.job_postings
(
    post_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    city_id integer NOT NULL,
    description character varying(500) NOT NULL,
    post_date date NOT NULL,
    post_deadline date NOT NULL,
    min_salary double precision NOT NULL,
    max_salary double precision NOT NULL,
    open_position_number character varying(50) NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (post_id)
);

CREATE TABLE public.job_seekers
(
    job_seeker_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birthdate date NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email_address character varying(250) NOT NULL,
    password character varying(250) NOT NULL,
    password_repeat character varying(250) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.verification
(
    verify_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (verify_id)
);

ALTER TABLE public.cv_informations
    ADD FOREIGN KEY ("cover_.id")
    REFERENCES public.cover_letter (cover_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (education_id)
    REFERENCES public.cv_educations (education_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (experience_id)
    REFERENCES public.cv_experiences (experience_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (image_id)
    REFERENCES public.cv_image (image_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (lang_id)
    REFERENCES public.cv_foreignlang (lang_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (skill_id)
    REFERENCES public.cv_skills (skill_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (social_id)
    REFERENCES public.cv_socialmedia (social_id)
    NOT VALID;


ALTER TABLE public.cv_informations
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_postings
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.job_postings
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (position_id)
    NOT VALID;


ALTER TABLE public.job_postings
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.verification
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;

END;
